export interface Car {
  id: string
  make: string
  model: string
  year: number
  trim: string
  price: number
  msrp?: number
  mileage: number
  exteriorColor: string
  interiorColor: string
  fuelType: string
  transmission: string
  engine: string
  horsepower: number
  torque: number
  drivetrain: string
  bodyStyle: string
  condition: "New" | "Used" | "Certified Pre-Owned"
  features: string[]
  images: string[]
  description: string
  shortDescription: string
  rating: number
  reviewCount: number
  featured: boolean
  seatingCapacity: number
  fuelTank: number
  cargoSpace: number
  curbWeight: number
  owners: number
}

export const cars: Car[] = [
  {
    id: "mercedes-amg-gt",
    make: "Mercedes-Benz",
    model: "AMG GT",
    year: 2023,
    trim: "Coupe",
    price: 118950,
    msrp: 124950,
    mileage: 1250,
    exteriorColor: "Obsidian Black",
    interiorColor: "Black Nappa Leather",
    fuelType: "Gasoline",
    transmission: "9-Speed Automatic",
    engine: "4.0L Biturbo V8",
    horsepower: 577,
    torque: 590,
    drivetrain: "RWD",
    bodyStyle: "Coupe",
    condition: "Certified Pre-Owned",
    features: [
      "AMG Performance Exhaust",
      "Burmester High-End Surround Sound System",
      "Head-Up Display",
      "AMG RIDE CONTROL Sport Suspension",
      "Panoramic Sunroof",
      "360-Degree Camera",
      "Heated and Ventilated Front Seats",
      "Wireless Charging",
      "Apple CarPlay and Android Auto",
      "Lane Keeping Assist",
      "Blind Spot Assist",
      "Active Brake Assist",
      "KEYLESS-GO",
      "AMG Carbon Fiber Trim",
      "20-inch AMG Forged Wheels",
    ],
    images: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/images-ZOsImxk1MEDJfBA1dXHhqOZFn0YNIX.jpeg",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/24c0113-033-source.jpg-uPHwtJREvsHjJZBQa2RL21QOjokXVY.jpeg",
      "/placeholder.svg?height=800&width=1200",
      "/placeholder.svg?height=800&width=1200",
      "/placeholder.svg?height=800&width=1200",
    ],
    description:
      "Experience the pinnacle of performance and luxury with this stunning Mercedes-AMG GT Coupe. This certified pre-owned vehicle delivers exhilarating performance with its 4.0L Biturbo V8 engine producing 577 horsepower. The sleek Obsidian Black exterior paired with the premium Black Nappa Leather interior creates an atmosphere of sophisticated sportiness.",
    shortDescription: "Certified Pre-Owned AMG GT with premium features and exhilarating performance",
    rating: 4.9,
    reviewCount: 28,
    featured: true,
    seatingCapacity: 2,
    fuelTank: 19.8,
    cargoSpace: 10.1,
    curbWeight: 3803,
    owners: 1,
  },
  {
    id: "rolls-royce-phantom",
    make: "Rolls-Royce",
    model: "Phantom",
    year: 2022,
    trim: "Extended Wheelbase",
    price: 535000,
    msrp: 565000,
    mileage: 3200,
    exteriorColor: "Tempest Blue",
    interiorColor: "Seashell White Leather",
    fuelType: "Gasoline",
    transmission: "8-Speed Automatic",
    engine: "6.75L Twin-Turbo V12",
    horsepower: 563,
    torque: 664,
    drivetrain: "RWD",
    bodyStyle: "Sedan",
    condition: "Used",
    features: [
      "Starlight Headliner",
      "Bespoke Audio System",
      "Rear Theater Configuration",
      "Picnic Tables",
      "Refrigerator Compartment",
      "Lambswool Floor Mats",
      "Rear Massage Seats",
      "Satellite Aided Transmission",
      "Night Vision with Pedestrian Recognition",
      "Active Cruise Control",
      "Panoramic Sky Lounge LED Roof",
      "Rear Privacy Suite",
      "Bespoke Interior Detailing",
      "Illuminated Treadplates",
      "Rolls-Royce Umbrella System",
    ],
    images: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/rolls_royce_phantom_top_10-eRN66cpyLL5G6gYm99b7q3ytiOjZMJ.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/A162414_large.jpg-goIaOENhJpAcnReD4LW4blN0Yr8zeA.jpeg",
      "/placeholder.svg?height=800&width=1200",
      "/placeholder.svg?height=800&width=1200",
      "/placeholder.svg?height=800&width=1200",
    ],
    description:
      "This Rolls-Royce Phantom Extended Wheelbase represents the ultimate in luxury motoring. The magnificent Tempest Blue exterior is complemented by a sumptuous Seashell White leather interior with bespoke detailing throughout. The 6.75L Twin-Turbo V12 engine delivers effortless power while the advanced suspension system ensures a 'magic carpet ride' experience.",
    shortDescription: "The pinnacle of luxury with bespoke features and unparalleled comfort",
    rating: 5.0,
    reviewCount: 12,
    featured: true,
    seatingCapacity: 5,
    fuelTank: 23.8,
    cargoSpace: 19.0,
    curbWeight: 5862,
    owners: 1,
  },
  {
    id: "rolls-royce-spectre",
    make: "Rolls-Royce",
    model: "Spectre",
    year: 2024,
    trim: "EV Coupe",
    price: 420000,
    mileage: 150,
    exteriorColor: "Andalusian Gold",
    interiorColor: "Black and Tan Leather",
    fuelType: "Electric",
    transmission: "Single-Speed Automatic",
    engine: "Dual Electric Motors",
    horsepower: 577,
    torque: 664,
    drivetrain: "AWD",
    bodyStyle: "Coupe",
    condition: "New",
    features: [
      "Planar Suspension System",
      "Starlight Doors",
      "Bespoke Audio System",
      "Illuminated Fascia",
      "Spirit of Ecstasy Hood Ornament",
      "Lambswool Floor Mats",
      "Heated and Ventilated Seats",
      "Massage Function",
      "Bespoke Clock",
      "Head-Up Display",
      "Night Vision",
      "Adaptive Cruise Control",
      "Suicide Doors",
      "Bespoke Interior Detailing",
      "22-inch Forged Wheels",
    ],
    images: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/2-spectre-unveiled-the-first-fully-electric-rolls-royce-front-3-4-1666037303.jpg-rJ3BNXR7r3mVyeBfya1p2QShoF8TDM.jpeg",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/best-car-interiors-6643b6c6b5a9a.jpg-NxkcQPH22q9pEFQ7jqwajR0SR6fOdJ.jpeg",
      "/placeholder.svg?height=800&width=1200",
      "/placeholder.svg?height=800&width=1200",
      "/placeholder.svg?height=800&width=1200",
    ],
    description:
      "Introducing the all-new Rolls-Royce Spectre, the marque's first fully-electric motor car. This ultra-luxury EV coupe combines Rolls-Royce's legendary craftsmanship with cutting-edge electric technology. The stunning Andalusian Gold exterior with contrasting Black and Tan leather interior creates a truly unique aesthetic. With dual electric motors producing 577 horsepower, the Spectre delivers the silent, instantaneous power that perfectly complements the Rolls-Royce experience.",
    shortDescription: "Rolls-Royce's first fully-electric ultra-luxury coupe with bespoke features",
    rating: 4.9,
    reviewCount: 7,
    featured: true,
    seatingCapacity: 4,
    fuelTank: 0,
    cargoSpace: 14.0,
    curbWeight: 6559,
    owners: 0,
  },
  {
    id: "lexus-lc-500",
    make: "Lexus",
    model: "LC 500",
    year: 2023,
    trim: "Inspiration Series",
    price: 105000,
    msrp: 115000,
    mileage: 2800,
    exteriorColor: "Structural Blue",
    interiorColor: "Semi-Aniline Blue Leather",
    fuelType: "Gasoline",
    transmission: "10-Speed Direct-Shift",
    engine: "5.0L V8",
    horsepower: 471,
    torque: 398,
    drivetrain: "RWD",
    bodyStyle: "Coupe",
    condition: "Used",
    features: [
      "Mark Levinson Reference Surround Sound",
      "Head-Up Display",
      "Limited Slip Differential",
      "Adaptive Variable Suspension",
      "Carbon Fiber Roof",
      "Heated and Ventilated Front Seats",
      "Lexus Safety System+",
      "Blind Spot Monitor",
      "Parking Assist",
      "Premium Triple-Beam LED Headlamps",
      "SmartAccess with Push-Button Start",
      "Lexus Enform App Suite",
      "Dynamic Radar Cruise Control",
      "Lane Keeping Assist",
      "21-inch Forged Alloy Wheels",
    ],
    images: [
      "/placeholder.svg?height=800&width=1200",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/best-car-interiors-6643b6c6b5a9a.jpg-NxkcQPH22q9pEFQ7jqwajR0SR6fOdJ.jpeg",
      "/placeholder.svg?height=800&width=1200",
      "/placeholder.svg?height=800&width=1200",
      "/placeholder.svg?height=800&width=1200",
    ],
    description:
      "This Lexus LC 500 Inspiration Series is a rare and exclusive grand touring coupe featuring the stunning Structural Blue exterior paint that took Lexus engineers over 15 years to develop. The naturally aspirated 5.0L V8 engine delivers a visceral driving experience with an intoxicating sound. The meticulously crafted interior features semi-aniline blue leather and Alcantara trim.",
    shortDescription: "Limited edition LC 500 with exclusive Structural Blue paint and premium features",
    rating: 4.8,
    reviewCount: 15,
    featured: false,
    seatingCapacity: 4,
    fuelTank: 21.7,
    cargoSpace: 5.4,
    curbWeight: 4280,
    owners: 1,
  },
  {
    id: "audi-a8",
    make: "Audi",
    model: "A8",
    year: 2023,
    trim: "L 60 TFSI Quattro",
    price: 98500,
    msrp: 110000,
    mileage: 5600,
    exteriorColor: "Vesuvius Gray Metallic",
    interiorColor: "Valcona Beige Leather",
    fuelType: "Gasoline",
    transmission: "8-Speed Tiptronic",
    engine: "4.0L Twin-Turbo V8",
    horsepower: 453,
    torque: 487,
    drivetrain: "AWD",
    bodyStyle: "Sedan",
    condition: "Used",
    features: [
      "Executive Rear Seat Package",
      "Bang & Olufsen 3D Advanced Sound System",
      "Panoramic Sunroof",
      "Rear Seat Entertainment System",
      "Predictive Active Suspension",
      "Night Vision Assistant",
      "Head-Up Display",
      "Audi Virtual Cockpit",
      "MMI Navigation Plus",
      "Valcona Leather Package",
      "Four-Zone Climate Control",
      "Ambient Lighting Package Plus",
      "Heated, Ventilated and Massage Seats",
      "Adaptive Cruise Assist",
      "20-inch 10-Spoke Wheels",
    ],
    images: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/A162414_large.jpg-goIaOENhJpAcnReD4LW4blN0Yr8zeA.jpeg",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/best-car-interiors-6643b6c6b5a9a.jpg-NxkcQPH22q9pEFQ7jqwajR0SR6fOdJ.jpeg",
      "/placeholder.svg?height=800&width=1200",
      "/placeholder.svg?height=800&width=1200",
      "/placeholder.svg?height=800&width=1200",
    ],
    description:
      "Experience first-class luxury with this Audi A8 L 60 TFSI Quattro. The extended wheelbase provides exceptional rear passenger space while the 4.0L Twin-Turbo V8 engine delivers impressive performance. The predictive active suspension system uses cameras to scan the road ahead and adjust the suspension accordingly, ensuring a smooth ride over any surface.",
    shortDescription: "Flagship luxury sedan with executive features and advanced technology",
    rating: 4.7,
    reviewCount: 22,
    featured: false,
    seatingCapacity: 5,
    fuelTank: 21.7,
    cargoSpace: 17.3,
    curbWeight: 4773,
    owners: 1,
  },
  {
    id: "mercedes-s-class",
    make: "Mercedes-Benz",
    model: "S-Class",
    year: 2023,
    trim: "S 580 4MATIC",
    price: 125000,
    msrp: 138000,
    mileage: 4200,
    exteriorColor: "Selenite Grey Metallic",
    interiorColor: "Macchiato Beige/Magma Grey Nappa Leather",
    fuelType: "Gasoline",
    transmission: "9-Speed Automatic",
    engine: "4.0L Biturbo V8",
    horsepower: 496,
    torque: 516,
    drivetrain: "AWD",
    bodyStyle: "Sedan",
    condition: "Used",
    features: [
      "Executive Rear Seat Package",
      "Burmester High-End 4D Surround Sound",
      "MBUX Interior Assistant",
      "Augmented Reality Navigation",
      "E-ACTIVE BODY CONTROL",
      "Rear-Axle Steering",
      "Digital Light Headlamps",
      "Energizing Comfort Package",
      "Warmth & Comfort Package",
      "Driver Assistance Package Plus",
      "Night Package",
      "Panorama Roof",
      "Active Ambient Lighting",
      "OLED Central Display",
      "21-inch AMG Multi-Spoke Wheels",
    ],
    images: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bmw_750li_xdrive_19_0.jpg-hLofRek2T44phgtKKSu6lqRc7vfCUl.jpeg",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/24c0113-033-source.jpg-uPHwtJREvsHjJZBQa2RL21QOjokXVY.jpeg",
      "/placeholder.svg?height=800&width=1200",
      "/placeholder.svg?height=800&width=1200",
      "/placeholder.svg?height=800&width=1200",
    ],
    description:
      "This Mercedes-Benz S 580 4MATIC represents the pinnacle of luxury and technology. The cabin features the latest MBUX system with augmented reality navigation and interior assistant. The E-ACTIVE BODY CONTROL suspension works with stereo cameras to scan the road ahead and adjust the suspension accordingly, providing an unparalleled smooth ride.",
    shortDescription: "Flagship luxury sedan with cutting-edge technology and supreme comfort",
    rating: 4.9,
    reviewCount: 31,
    featured: true,
    seatingCapacity: 5,
    fuelTank: 22.2,
    cargoSpace: 18.7,
    curbWeight: 4775,
    owners: 1,
  },
]
